[project]
name = "starcommand"
version = "0.1.0"
description = "A be minecraft command editor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.19.0",
]

[tool.mypy]
explicit_package_bases = true
